import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css"; 
import TopStrip from "./components/TopStrip";
import MainNavbar from "./components/MainNavbar";
import HeroOverlay from "./components/HeroOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // normal to bold weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable}antialiased`}
      >
        <TopStrip/>
        <MainNavbar/>
        <HeroOverlay/>
        {children}
      </body>
    </html>
  );
}
